apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    name: db-deployment
    app: voting-app
    tier: backend

spec:
  replicas: 1
  selector:
    matchLabels:
     name: db
     app: voting-app
     tier: backend

  template:
      metadata:
        name: db
        labels:
          name: db
          app: voting-app
          tier: backend
      spec:
        containers:
          - name: db-container
            image: postgres:9.4
            ports:
              - containerPort: 5432
            env:
              - name:  POSTGRES_USER
                value: "postgres"
              - name: POSTGRES_PASSWORD
                value: "postgres"