apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    name: result
    app: voting-app
    tier: frontend
spec:
  type: NodePort
  ports:
    - name: port1
      port: 80
      nodePort: 30001
      targetPort: 80
    - name: port2
      port: 5858
      nodePort: 30003
      targetPort: 5858
  selector:
    name: result
    app: voting-app
    tier: frontend
