apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    name: vote
    app: voting-app
    tier: frontend
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     nodePort: 30000

  selector:
    name: vote
    app: voting-app
    tier: frontend